### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by SleepyBrett** [google/go-jsonnet#239]
```
 ~/Dropbox/go/src/github.com/google/go-jsonnet/jsonnet   master  go build
# github.com/google/go-jsonnet/jsonnet
./cmd.go:497:60: color.New(color.FgRed).Fprintf undefined (type *color.Color has no field or method Fprintf)

 ~/Dropbox/go/src/github.com/google/go-jsonnet/jsonnet   master  go version
go version go1.10.2 darwin/amd64
```

Some drift in the color library?

**Comment by garethr** [comment]
I just ran into this and submitted a fix to the README: https://github.com/google/go-jsonnet/pull/242

**Comment by sbarzowski** [comment]
Thanks for pointing this out.

The reason it happens is that only the CLI depends on the color package. Formally CLI is a separate package from `github.com/google/go-jsonnet`. Jsonnet library doesn't depend on the CLI (only the other way around), so `go get github.com/google/go-jsonnet` doesn't install dependencies of the CLI.

**Comment by SleepyBrett** [comment]
ah gotcha!

**Comment by mmolnar** [comment]
Sorry but this still does not work for me, library `github.com/fatih/color` really does not have method Fprintf so `color.New(color.FgRed).Fprintf` will throw an error even if you run go get.

**Comment by sbarzowski** [comment]
I think it does - https://github.com/fatih/color/blob/master/color.go#L214 and it worked for us for a while. Any chance you have some very ancient version of `github.com/fatih/color` and you could update? If that's not it, please paste the details (exact versions, and error message), so we can debug - since we have "works on my machine" kind of situation.

**Comment by mmolnar** [comment]
That was my error, you are right, sorry for bothering you.
