### ISSUE TITLE
base64 issue with £ char ?

### ISSUE THREAD

**Issue by pmcgrath** [google/go-jsonnet#267]
I am trying to base64 encode some password data that includes a £ symbol but can see it failing

p.jsonnet
```
local config = {
  password: "12$£1"
};

{
  clearField: config.password,

  # This is the issue
  base64Field: std.base64(config.password),
}
```

When I run I see I see
```
{
   "base64Field": "MTIkozE=",
   "clearField": "12$£1"
}
```

Issue is with the base64Field, so if i use [jq](https://stedolan.github.io/jq/tutorial/) and decode I see this
```
jsonnet p.jsonnet | jq -r .base64Field | base64 -d

12$1
```

It has lost the £ symbol

Using bash it does not drop the £
```
echo 12$£1 | base64 | base64 -d
```

Is this a potential bug or am I missing something ?

**Comment by sbarzowski** [comment]
Thanks for opening this issue.

You can get the standard encoding compatible with `base64` command using `std.base64(std.encodeUTF8(12$£1))`. You can decode it in Jsonnet with `std.decodeUTF8(std.base64DecodeBytes("MTIkwqMx"))`.

The default behavior is an unfortunate historical decision. Base64 is an operation defined on bytes, but there are multiple ways of representing Unicode characters as bytes. Jsonnet doesn't use the standard encoding in base64, but instead treats codepoints as bytes (and disallows codepoints > 255). This is not a very good way to do it, but we kept it for compatibility reasons. 

@sparkprime What do you think of using UTF8 encoding when strings are passed to `base64`? Or disallowing strings completely (so that explicit encoding decision needs to be made)?

**Comment by pmcgrath** [comment]
@sbarzowski Thanks for the explanation, can I close this issue so based on above

**Comment by sbarzowski** [comment]
Yes, let's close it.

**Comment by pmcgrath** [comment]
Explanation given above going to close the issue
