### ISSUE TITLE
Positional argument after a named argument is not allowed

### ISSUE THREAD

**Issue by lihaoyi-databricks** [google/go-jsonnet#314]
```bash
$ cat foo.jsonnet
local f(x, y = 123, z) = x + y + z;
f(1, 2, 3)

$ jsonnet/bazel-bin/cmd/jsonnet foo.jsonnet
6

$ ./sjsonnet.jar foo.jsonnet
6

$ go-jsonnet/jsonnet  foo.jsonnet
foo.jsonnet:1:21-22 Positional argument after a named argument is not allowed

local f(x, y = 123, z) = x + y + z;
```

This seems to be a new error in the go-jsonnet implementation. The old C++ google/jsonnet or Scala databricks/sjsonnet don't have any problems with no-default-value params like `z` following with-default-value params like `y`. Anyway, the message doesn't make much sense because whether an argument as a default or not, it can always be passed either positionally or via its name.

This is on the following version:

```bash
$ go-jsonnet/jsonnet
Jsonnet commandline interpreter v0.13.0
```

**Comment by sbarzowski** [comment]
Interesting. I believe the spec forbids this, unless I'm reading it wrong:

<img width="350" alt="Screen Shot 2019-09-09 at 09 34 23" src="https://user-images.githubusercontent.com/683828/64511679-19943d80-d2e5-11e9-8516-2d09a207c4b7.png">

<img width="358" alt="Screen Shot 2019-09-09 at 09 26 37" src="https://user-images.githubusercontent.com/683828/64511157-fe74fe00-d2e3-11e9-9029-ec217b64d4a5.png">
(from https://jsonnet.org/ref/spec.html)

@sparkprime Thoughts?

**Comment by sparkprime** [comment]
Yes it is not supposed to allow that, as it's designed to work the same way as Python.  It's funny that two implementations both have the same "bug" when the spec is fairly explicit about how it should work.

```
SyntaxError: non-default argument follows default argument
```

So we need to figure out whether this accidental feature is useful or dangerous (potentially both), because we need to decide whether or not to add it to the spec and implement it in go-jsonnet, or declare it invalid and remove it from everywhere...

I note that the semantics is a bit weird, as I'd expect this to default the y and satisfy the z but it instead errors out.

```jsonnet
local f(x, y='Y', z) = [x, y, z];
f('x', 'z')
```

It seems like it would be hard to modify code that uses this by re-arranging params to put the defaulted ones at the end.  However, adding more defaults (e.g. null) should be possible because that would not change the behavior of any callers that already work.

**Comment by sparkprime** [comment]
It's also inconsistent in C++ Jsonnet because you can do it at definition time but not at call time:

```bash
dcunnin@dcunnin1:~$ jsonnet -e "local f(x, y='Y', z) = [x, y, z]; f('x', y='y', 'z')"
RUNTIME ERROR: internal error: got positional param after named at index 2
        <cmdline>:1:35-53
```

**Comment by sparkprime** [comment]
Li, do you know how often this feature is used in your code base?

**Comment by sparkprime** [comment]
Ok the way to change code to avoid using this feature is:
```jsonnet
local f(x, y = 123, z=error "z is required") = x + y + z;
```

**Comment by igorpeshansky** [comment]
Seems like an easy workaround, so it's better to fix the implementation to match the spec. I wonder if it's also possible to create a rewriter that would add that `=error` default automatically...

**Comment by lihaoyi-databricks** [comment]
> It's funny that two implementations both have the same "bug" when the spec is fairly explicit about how it should work.

Haha it's not surprising at all; I explicitly made `databricks/sjsonnet` byte-for-byte compatible with `google/jsonnet`, so any places where the spec and implementation disagreed, I followed what the implementation did!

I think our codebase uses it quite a lot, for better or for worse. We have quite a lot of functions that take a lot of params (e.g. 10-20), and the parameters have their own natural grouping and ordering (e.g. kubernetes-related things, database-related things, monitoring-related things) that doesn't cleanly map to "all things with default values live at the end of the list". Adding a bunch of `x = error "x is required"` seems like a bit too much boilerplate/inconvenience for what's otherwise a pretty straightforward pattern. Maybe we're used to it because Scala lets you have defaults interspersed in an argument list in any order:

```scala
def f(x: Int = 0, y: Int) = x + y
```

Since it's a pretty trivial transform, we might just maintain compatibility with this in our own implementation, whether by leaving unchanged or adding a `--sloppy` flag that does the AST-transform transparently to the user in case other people using Sjsonnet prefer to have more strict handling

**Comment by sbarzowski** [comment]
> we might just maintain compatibility with this in our own implementation

Creating incompatible dialects is exactly what we are trying to avoid here. Even if it's behind the flag it is something that any tools would need to take into account.  keep Jsonnet a single language.

When you put required params after the optional ones, that's effectively you get "required named params", unless you are passing previous optional arguments positionally. In general "required named arguments" make sense as a feature and it's one of the things they added to Python3, with a specific rationale.

So if it's so important for Databricks codebase (and presumably others as well), perhaps we can just support it officially and even maybe improve it so that you can explicitly state which params are required and which are not.

**Comment by lihaoyi-databricks** [comment]
Yes, for those functions with large numbers of parameters we do indeed pass everything as a named argument, as trying to figure out off-by-one errors when you have 20 different positional arguments is a nightmare. Having an explicit syntax to allow/enforce named argument passing sounds reasonable

**Comment by sparkprime** [comment]
Before we implemement that, we'd have to implement varargs though (which are also useful of course).

**Comment by sbarzowski** [comment]
> we'd have to implement varargs though

Hmmm... I don't see how it has anything to do with varargs...

**Comment by sparkprime** [comment]
Because the `*` is syntax sugar for `*unused` and `assert len(unused)==0`

**Comment by sbarzowski** [comment]
Well, in Python yes, but we don't have to do it this way. I just used Python's syntax as an example, but for us `*` can have a special meaning there or even have a completely different syntax.

**Comment by sparkprime** [comment]
Ok I'm convinced the current C++ behavior is useful, safe, and has a precedent (in Scala). In future we could make it more Python3-like but that's no reason to block fixing this divergence.

We will still not allow this:
```jsonnet
local f(x, y='Y', z) = [x, y, z]; f('x', y='y', 'z')
```

Which is an inconsistency between call and definition but it can be justified by the desire to force the caller to use positional params for greater clarity.
