### ISSUE TITLE
Development: Builtin Return Bytes[]

### ISSUE THREAD

**Issue by ghostsquad** [google/go-jsonnet#345]
I'm working on moving `base64DecodeBytes` into native Go, but I'm having a problem figuring out how to return the `byte[]`. I can't use `makeValueArray` as it expects a `*cachedThunks`.

It seems like maybe I need to convert each byte into a `*cachedThunk`. This part looks complicated, and I have failed to find a decent example of this that I can use.

**Comment by sbarzowski** [comment]
Yes, each byte needs to be wrapped in cachedThunk. A helper function `readyThunk` can be used for that: https://github.com/google/go-jsonnet/blob/master/builtins.go#L465. 

Some context:
The point of thunks there is that Jsonnet is lazy and each element of the array will (in general) be calculated only when it's requested - so array elements are thunks rather than values. Generally `thunk` is a thing that can be evaluated to a value. And `cachedThunk` is a thunk which saves the result after first calculation. When a value is already available - "ready" - it's a special, simple case of thunk, hence function "readyThunk".

**Comment by ghostsquad** [comment]
thank you for the explanation! Let me see if I can make this work, and if I have additional questions, I'll post them here or close this once I have a working PR.

**Comment by ghostsquad** [comment]
@sbarzowski I'm confused. You pointed at:

```
func makeValueBoolean(v bool) *valueBoolean
```

but a `byte` is not a boolean value

**Comment by sbarzowski** [comment]
Argh, sorry., Ofc you need intToValue after all, you have bytes not booleans.

**Comment by ghostsquad** [comment]
see #346 - got it working!
