### ISSUE TITLE
Regresion from C++ jsonnet - local variables during comprehension

### ISSUE THREAD

**Issue by aruiz14** [google/go-jsonnet#358]
While trying to upgrade the `go-jsonnet` library from `v0.12.0` to `v0.14.0`, I noticed the results produced from both versions differed.
Although I noticed this while rendering many jsonnet files, I was able to reduce it to the point of just this small reproducer:

```
local data = {
  a: 'A',
  b: 'B',
};

local process(input) = {
  local v = input[k],
  [k]: v
  for k in std.objectFields(input)
};

process(data)
```

I also, identified the commit(s) I believe introduced the regression as 33b6dcfa531556502e226c24090622fb3016ff68 (actually next one: 83ed0b939f98b8edab6626312460dc3fa2565171, since that one won't build). 
This makes versions 0.13.0 and 0.14.0 to include this bug, which is not present in the C++ jsonnet version.

I ran the reproducer with multiple versions of go-jsonnet and these are the results

```
# v0.12.1
# 181c86d (last commit without this bug)
# C++ Jsonnet v0.14.0

{
   "a": "A",
   "b": "B"
}

# 83ed0b (first buildable commit including this bug)
# v0.13.0
# v0.14.0
{
   "a": "B",
   "b": "B"
}
```

**Comment by sbarzowski** [comment]
Thanks a lot for reporting. I think I see what's going on. I didn't know that you can use the index variable in object-locals in an object comprehensions, but the specification seems to explicitly allow this:
![image](https://user-images.githubusercontent.com/683828/73168386-0221e980-40fa-11ea-9b01-dcc82e6b5b52.png)


In the newer versions of go-jsonnet locals are treated similar to fields (they are kept only once in the object, etc.). This is a very good thing for performance. Unfortunately the assumption that an object local is a single value for an object is broken here, because the same object-local name (`v`) refers to different values here.

I intend to fix it, but it may be a bit tricky. Also, object comprehensions generally seem to be quite a bug magnet, so maybe it's time for an overhaul there. 

As a workaround you can move the locals into the field:

```
local data = {
  a: 'A',
  b: 'B',
};

local process(input) = {
  [k]: 
       local v = input[k];
       v
  for k in std.objectFields(input)
};

process(data)
```

**Comment by aruiz14** [comment]
Thanks for the quick turnaround! Also for such a detailed explanation and the workaround (which I didn't know I could use).

IMHO the syntax is indeed confusing and makes the code less readable, so I find your suggestion to be much clearer.
I will change my `.jsonnet` files to use this alternative, but it will be great it the bug could be fixed at some point to prevent any further issues in the future, in case somebody else tries to use that syntax.

Thanks again!

**Comment by sparkprime** [comment]
Thanks for the report.  There isn't much benefit in allowing the local in that position unless we also allow multiple fields.  But it's not surprising this hasn't been noticed until now.

**Comment by camh-anz** [comment]
Another syntax you can use here that may read better:
```
local data = {
  a: 'A',
  b: 'B',
};

local process(input) = {
  [k]: v
  for k in std.objectFields(input)
  for v in [input[k]]
};

process(data)
```
