### ISSUE TITLE
std.foldr fails when std.foldl don't

### ISSUE THREAD

**Issue by DifferentialOrange** [google/go-jsonnet#398]
`Jsonnet commandline interpreter v0.15.0`

I use go-jsonnet with my own [grafonnet](https://github.com/grafana/grafonnet-lib) fork. The following code (`panels/health.libsonnet` 235-251):
```
):: std.foldr(function(graph, host)
    graph.addTarget(
      influxdb.target(
        rawQuery=true,
        query='query'
      )
    ),
    ['host1', 'host2'],
    tablePanel.new(
      title=title,
      description=description,
      datasource=datasource,

      width=width,
      height=height
    )
  )
```
fails with incomprehensible error
```
RUNTIME ERROR: Unexpected type string, expected number
	panels/health.libsonnet:236:5-20	function <anonymous>
	<std>:766:24-47	thunk from <function <aux>>
	<std>:766:9-57	function <aux>
	<std>:767:5-46	function <anonymous>
	panels/health.libsonnet:(235:7)-(251:4)	function <anonymous>
	./examples/myboard.jsonnet:(181:3)-(187:4)	thunk from <thunk <health_overview> from <$>>
	vendor/grafonnet/dashboard.libsonnet:80:13-25	function <anonymous>
		
	During manifestation
```
but the same code using `std.foldl` instead of `std.foldr` compiles without any errors.

**Comment by sbarzowski** [comment]
Thanks for reporting. In general you can get different results in `foldl` and `foldr` of course. In your case I think it works one way and not the other because of the order of the arguments. With `foldl` the function you passed is called with accumulator as the first argument and array element as the second one. For `foldr` it's the opposite, the first argument is the array element and the second is the accumulator.

If you wonder why the order of the arguments is like that it makes sense if you expand the fold:
`foldl(f, [1, 2, 3], init)` is equivalent to `f(f(f(init,1),2),3)`
`foldr(f, [1, 2, 3], init)` is equivalent to `f(1,f(2,f(3,init)))`

Let me know if that resolves your issue. 

BTW we should improve the docs for that.

**Comment by DifferentialOrange** [comment]
Yes, it resolved my issue, thank you!
