### ISSUE TITLE
Proposal: use yaml-like syntax instead of json-like

### ISSUE THREAD

**Issue by steeling** [google/go-jsonnet#469]
Jsonnet is clearly in a json-like syntax, and even addresses the comparison with yaml here https://jsonnet.org/articles/comparisons.html. Since this is mostly humans editing the jsonnet files (presumably), and that doc mentions yaml is a nice choice, I was wondering how much work it might be to extend the parser to generate an ast for jsonnet out of yaml.

I see the 1 + 1 issue mentioned, but I think rewriting to addition is fine. In fact this playground shows the string representation is in tact https://play.golang.org/p/wbeotXHTFU0, so if that is a libyaml constraint, then even go-yaml isn't following it.

Anyways just a thought, I understand its a large undertaking, but was curious to discuss

**Comment by sbarzowski** [comment]
You could in principle create a Jsonnet variant which has YAML-ish syntax while keeping the semantics. There are a couple problems, though:
- YAML syntax is not particularly well defined and each parser implements a slightly different variant of it – so we would need to formalize it and probably restrict it in many ways.
- YAML has many problems, e.g. `no` is often interpreted as `false` in a way that confuses users. That would need to be clarified and formalized.
- We could not use any existing YAML parser, because (a) we would need to extend syntax to support Jsonnet stuff (e..g functions) and (b) we would need to be more rigorous about the accepted syntax and its interpretation than any parser that I know of.
- Using two different kinds of syntax is a recipe for fragmenting the community. It's better to be consistent.

So, going towards complete YAML-like syntax is a non-starter. If you have some specific cases where JSON-like syntax is inconvenient we can discuss if and how we can make Jsonnet more ergonomic.

And if the motivation for it is supporting migrating existing YAML codebases to Jsonnet, you can try automatic conversion (preserving comments!): https://github.com/waisbrot/yaml2jsonnet.
