### ISSUE TITLE
Feature request: standard library function to produce "compressed" / "minimal whitespace" json

### ISSUE THREAD

**Issue by mark-rushakoff** [google/go-jsonnet#471]
We have a place in our code, where we want to emit a stringified JSON value. Suppose the intended output looks something like:

```json
{
   "foo": "bar",
   "myJSONValue": "{\"hello\":\"world\",\"one\":1}"
}
```

When we use `std.manifestJsonEx(obj, '')`, the stringified JSON contains newlines, and spaces between key-value pairs, e.g. 

```
{
   "foo": "bar",
   "myJSONValue": "{\n\"hello\": \"world\",\n\"one\": 1\n}"
}
```

Of course, our real application of this is serializing an object with many key-value pairs, and the value is intended to be consumed by a machine.

We considered using string replacement to trim some of the whitespace away, but that seems like a brittle solution.

Would you be open to adding a new function like `manifestJsonCompressed` or `manifestJsonMinimized` which would result in the former output, without unnecessary whitespace?

**Comment by davidreuss** [comment]
would `std.toString(obj)` work for your purpose?

**Comment by mark-rushakoff** [comment]
That emits `"{\"hello\": \"world\", \"one\": 1}"`, which is an improvement over `std.manifestJsonEx`'s newlines. It didn't occur to me to look to `std.toString`, so thank you for that suggestion.  I think a version that doesn't include the whitespace in the tokens is still a reasonable ask.

**Comment by sbarzowski** [comment]
Yes, I think `manifestJsonMinimized` would be a good addition to stdlib and we would happily accept a PR (it would need to be added around here: https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L917).

Using naive string replacement to remove spaces is generally a bad idea, because it may trim them inside strings. Stripping newlines should be fine, although a little ugly.

Also, generally writing a custom `manifestSomething` functions is quite easy (e.g. 35 lines of very straightforward code for JSON). Sp, if you ever need to have some special output format, you can, without explicit stdlib support.

**Comment by hanyucui** [comment]
@sbarzowski If no one has taken this, can I give it a try?

**Comment by sbarzowski** [comment]
Sure, great!

**Comment by hanyucui** [comment]
@sbarzowski Now that google/jsonnet#871 is merged, I will augment the native implementation of `std.manifestJsonEx` in a similar way.
