### ISSUE TITLE
Issues with Large Numbers

### ISSUE THREAD

**Issue by johnclara** [google/go-jsonnet#547]
Seeing weird conversions with large numbers that happen silently

```
jsonnet -e 5746521940354690803
```
returns
```
5746521940354691072
```

**Comment by johnclara** [comment]
over max size: https://jsonnet.org/ref/language.html#Number

**Comment by sbarzowski** [comment]
Well, the numbers in Jsonnet are IEEE754 doubles. So this is by design. I wouldn't mind adding unlimited size integers at some point, but it's unclear how to do it in an elegant and backwards compatible manner.

BTW a lot of JSON parsers have trouble with bigints (i.e. also treat numbers as doubles), so it's best to avoid them in output format.
